package gui;

import player.Player;
import application.Tournament;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import transport.PlayerToPlayerUIMapper;
import transport.PlayerUiModel;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class StandingsGui {
    private JLabel jLabelStandings;
    private JTable standingsTable;
    private JPanel standingsPanel;
    private DefaultTableModel tableModel;
    private final Tournament tournament;

    public StandingsGui(Tournament tournament) {
        this.tournament = tournament;
        setUpTable();
        refreshGamesList();
    }

    public JPanel getStandingsPanel() {
        return standingsPanel;
    }

    private void setUpTable() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableModel.addColumn("PlayerId");
        tableModel.addColumn("Name");
        tableModel.addColumn("Score");
        tableModel.addColumn("Buchholz Score");
        tableModel.addColumn("SB Score");

        standingsTable.setModel(tableModel);
        standingsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

    }

    public void refreshGamesList() {
        PlayerToPlayerUIMapper playerToPlayerUIMapper = new PlayerToPlayerUIMapper();

        tableModel.setRowCount(0);

        for (Player player : tournament.getPlayerService().getRankedPlayers()) {
            PlayerUiModel playerUiModel = playerToPlayerUIMapper.map(player);
            tableModel.addRow(new Object[]{playerUiModel.getId(), playerUiModel.getFullName(), playerUiModel.getScore(), playerUiModel.getBuchholzScore(), playerUiModel.getSonnebornBergerScore()});
        }

        standingsPanel.revalidate();
        standingsPanel.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        standingsPanel = new JPanel();
        standingsPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        jLabelStandings = new JLabel();
        Font jLabelStandingsFont = this.$$$getFont$$$(null, Font.BOLD, 26, jLabelStandings.getFont());
        if (jLabelStandingsFont != null) jLabelStandings.setFont(jLabelStandingsFont);
        jLabelStandings.setText("Standings");
        standingsPanel.add(jLabelStandings, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        standingsPanel.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        standingsTable = new JTable();
        scrollPane1.setViewportView(standingsTable);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return standingsPanel;
    }

}
