package gui;

import Player.Player;
import application.Tournament;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import transport.PlayerToPlayerUIMapper;
import transport.PlayerUiModel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class TournamentGui extends JFrame {
    private JTable registeredPlayerTable;
    private JButton addPlayerButton;
    private JButton startButton;
    private JPanel tournamentPanel;

    private final Tournament tournament;

    private boolean registerInProgress;

    private DefaultTableModel tableModel;

    public TournamentGui(Tournament tournament) {
        this.tournament = tournament;
        registerInProgress = false;
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(tournamentPanel);
        setTitle("Tournament-Manager");
        setSize(500, 500);
        setVisible(true);

        setUpTable();

        addPlayerButton.addActionListener(e -> {
            if (!registerInProgress) {
                new RegisterPlayerGui(tournament, this);
                setRegisterInProgress(true);
            }
        });
    }

    private void setUpTable() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Player");
        tableModel.addColumn("Club");
        tableModel.addColumn("ELO");
        tableModel.addColumn("DWZ");
        registeredPlayerTable.setModel(tableModel);
    }


    public void setRegisterInProgress(boolean registerInProgress) {
        addPlayerButton.setEnabled(!registerInProgress);
        this.registerInProgress = registerInProgress;
    }

    public void refreshPlayerList(Player player) {
        PlayerToPlayerUIMapper playerToPlayerUIMapper = new PlayerToPlayerUIMapper();


        PlayerUiModel playerUiModel = playerToPlayerUIMapper.map(player);
        tableModel.addRow(new Object[]{playerUiModel.getFullName(), playerUiModel.getClubName(), playerUiModel.getElo(), playerUiModel.getDwz()});


        revalidate();
        repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tournamentPanel = new JPanel();
        tournamentPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        tournamentPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        tournamentPanel.add(scrollPane1, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        registeredPlayerTable = new JTable();
        scrollPane1.setViewportView(registeredPlayerTable);
        addPlayerButton = new JButton();
        addPlayerButton.setText("Add Player");
        tournamentPanel.add(addPlayerButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startButton = new JButton();
        startButton.setText("Start");
        tournamentPanel.add(startButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tournamentPanel;
    }

}
